//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Data.DataTable GetData(string nameTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync(string nameTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckConnection", ReplyAction="http://tempuri.org/IService1/CheckConnectionResponse")]
        bool CheckConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckConnection", ReplyAction="http://tempuri.org/IService1/CheckConnectionResponse")]
        System.Threading.Tasks.Task<bool> CheckConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumRow", ReplyAction="http://tempuri.org/IService1/GetNumRowResponse")]
        int GetNumRow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumRow", ReplyAction="http://tempuri.org/IService1/GetNumRowResponse")]
        System.Threading.Tasks.Task<int> GetNumRowAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp.ServiceReference1.IService1>, WindowsFormsApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetData(string nameTable) {
            return base.Channel.GetData(nameTable);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync(string nameTable) {
            return base.Channel.GetDataAsync(nameTable);
        }
        
        public bool CheckConnection() {
            return base.Channel.CheckConnection();
        }
        
        public System.Threading.Tasks.Task<bool> CheckConnectionAsync() {
            return base.Channel.CheckConnectionAsync();
        }
        
        public int GetNumRow() {
            return base.Channel.GetNumRow();
        }
        
        public System.Threading.Tasks.Task<int> GetNumRowAsync() {
            return base.Channel.GetNumRowAsync();
        }
    }
}
